// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lydpfdfonedzryarkptk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZHBmZGZvbmVkenJ5YXJrcHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTA1NzgsImV4cCI6MjA1NzQ2NjU3OH0.9xBIfj9FmNYMbJwKPeia-zQskhffpOHUuhFsOQh0HOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);